apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: crontest
  name: crontest
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: crontest
        spec:
          containers:
          - image: busybox
            name: crontest
            resources: {}
            command: ["date; echo Hello"]
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
